title: Wonkyo Choe
position: Ph.D. Student
affiliation: University of Virginia
email: bfr4xr (at) virginia.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/
github_link: https://github.com/wonkyoc/wonkyoc.github.io
linkedin: https://www.linkedin.com/in/wonkyo-choe
avatar: ./assets/img/profile_2.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
